version: '3'

volumes:
  db-data:

services:
  # railsの設定
  web:
    build: .

    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    volumes:
      - '.:/rails-docker'
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  # postgresqlの設定
  db:
    image: postgres:12
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
